### ISSUE TITLE
Before copying game data, validate if user selected correct directory

### ISSUE THREAD

**Issue by a1batross** [Velaron/xash3d-fwgs#1]
Воспроизводил сам позавчера, на билде соответствующей давности.

`valve` лежала в корне внешнего хранилища, логично корень выбрать нельзя, поэтому я выбрал внутренности самой valve. Лаунчер без вопросов скопировал их все во внутреннее хранилище приложения, с некорректной структурой папок. Естественно после окончания работы Half-Life он не нашел.

Тогда я очистил приложение, создал в корне временную папку, в неё перетянул `valve` и указал временную папку в лаунчере. Лаунчер отказался копировать файлы вообще, без ошибки, просто пустой прогрессбар и неотформатированные строчки `files_total` и `current_file`.

**Comment by Velaron** [comment]
Собственно внутренности самой valve и надо выбирать, и это указано в диалоге который ты подтвердил, но попытаюсь сделать всё интуитивнее

**Comment by a1batross** [comment]
Да, но почему-то он скопировал не туда. То есть после копирования ничего не
появилось, только после того, как я самостоятельно скопировал через файл
менеджер, заработало.

вт, 18 апр. 2023 г., 11:22 Bohdan Shulyar ***@***.***>:
