### ISSUE TITLE
No Parent Directory nor the Search icon

### ISSUE THREAD

**Issue by Nin10doGMod** [Velaron/xash3d-fwgs#10]
![Screenshot_20230508-114756_Files](https://user-images.githubusercontent.com/59216753/236908612-5131cdc1-80b6-4930-a924-15f009793308.jpg)
Hello, I couldn't go the directory, "_/storage/emulated/0/xash_", where the Xash folder is. Can you add the Parent Directory and Search to Xash3D FWGS?

**Comment by Velaron** [comment]
This UI is a part of Android and it can't be modified or replaced, Internal Storage may be hidden in the 3-dot menu.
