### ISSUE TITLE
In new launcher, folder icon button "Install" doesn't do anything

### ISSUE THREAD

**Issue by a1batross** [Velaron/xash3d-fwgs#2]
On my phone, I don't even have a default Android file manager, and the button doesn't do anything for me.

However, a simple application like this https://play.google.com/store/apps/details?id=com.marc.files does open Android built-in file manager and I can access Xash files from it. Maybe it's possible to decompile it to figure out what it does.

**Comment by Velaron** [comment]
That's what I was inspired by and what it's supposed to do in the future
