### ISSUE TITLE
Asheep mod not working

### ISSUE THREAD

**Issue by Cruzejer123** [Velaron/xash3d-fwgs#21]
I go the the part that leads down to the security guard office outside of the dormitories at the beginning state and just as I get near the door, it glitches out and I am inside of the control panel when an animation is supposed to play out but it's bugs out and I am stuck outside and can't go out and the door that doesn't let u out  well I can go out and wander the rest of the level but I can't progress any further fix plz

**Comment by Velaron** [comment]
Use this and old engine
https://www.moddb.com/games/xash3d-android/downloads/azure-sheep-android-port
