### ISSUE TITLE
Engine freezes on startup

### ISSUE THREAD

**Issue by Vladislav4KZ** [Velaron/xash3d-fwgs#6]
Движок зависает во время запуска.

Старый баг, который проявлялся ещё на старом лаунчере версии 0.20.1

Решается несколькими попытками перезапуска ксаша с принудительной остановкой.

[engine.log](https://github.com/Velaron/xash3d-fwgs/files/11264934/engine.log)

Кроме того, если движок всё-таки запустился, он может зависнуть во время запуска сервера или начала новой одиночной игры.

Но во время подключения к уже созданному серверу, ксаш никогда не зависает.

**Comment by Velaron** [comment]
должно починиться

**Comment by Vladislav4KZ** [comment]
> должно починиться

Неужели, оно теперь действительно не зависает! Хорош!
